name: tokenflix
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  provider: ^6.0.3
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.2
  flex_color_scheme: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
